[package]
name = "rust_actix_framework_example"
version = "0.1.0"
authors = ["David DiMaria <info@collectivesessions.com>"]
edition = "2018"

[dependencies]
rust_actix_framework = { path = "../" }
actix-cors = "0.2.0"
actix-rt = "1"
actix-web = "2"
dotenv = "0.14"
env_logger = "0.6"
listenfd = "0.3"


[features]
cockroach = []
mysql = []
postgres = []
sqlite = []
default = ["mysql"]